import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateSalarySlipPDF = async (record: any, company: any) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(250, 204, 21); // #FACC15
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(company.name.toUpperCase(), 15, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL SALARY SLIP', 15, 32);

  doc.setFontSize(16);
  doc.text('PAYSLIP', 160, 25);
  doc.setFontSize(10);
  doc.text(record.period.toUpperCase(), 160, 32);

  // Employee details
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('EMPLOYEE NAME', 15, 55);
  doc.text('EMAIL ADDRESS', 110, 55);
  
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(record.employeeName.toUpperCase(), 15, 62);
  doc.text(record.employeeEmail, 110, 62);

  // Table
  const tableData = [
    ['EARNINGS', 'AMOUNT'],
    ['Base Salary', `Rs ${record.baseSalary.toLocaleString()}`],
    ['Bonuses / Allowances', `Rs ${record.bonuses.toLocaleString()}`],
    ['', ''],
    ['DEDUCTIONS', 'AMOUNT'],
    ['Adjustments', `Rs ${record.deductions.toLocaleString()}`],
    ['', ''],
    ['TOTAL NET PAY', `Rs ${record.netPay.toLocaleString()}`]
  ];

  autoTable(doc, {
    startY: 75,
    head: [['Description', 'Amount']],
    body: [
      ['Base Salary', `Rs ${record.baseSalary.toLocaleString()}`],
      ['Bonuses & Allowances', `Rs ${record.bonuses.toLocaleString()}`],
      ['Deductions', `- Rs ${record.deductions.toLocaleString()}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    styles: { font: 'helvetica', fontSize: 10 },
    columnStyles: {
      1: { halign: 'right', fontStyle: 'bold' }
    }
  });

  // Summary Box
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFillColor(243, 244, 246);
  doc.rect(120, finalY, 75, 25, 'F');
  doc.setDrawColor(0, 0, 0);
  doc.rect(120, finalY, 75, 25, 'S');

  doc.setFontSize(9);
  doc.text('NET TAKE HOME', 125, finalY + 10);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Rs ${record.netPay.toLocaleString()}`, 125, finalY + 20);

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  const dateStr = new Date().toLocaleDateString();
  doc.text(`Generated by Radical Ledger on ${dateStr}`, 15, 285);

  return doc.output('arraybuffer');
};

export const generateCustomInvoicePDF = async (invoice: any, company: any) => {
  const doc = new jsPDF();

  // Draw an elegant top accent bar
  doc.setFillColor(250, 204, 21); // #FACC15
  doc.rect(0, 0, 210, 6, 'F');

  // Header Background
  doc.setFillColor(15, 23, 42); // deep slate/navy (#0F172A)
  doc.rect(0, 6, 210, 44, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 28);
  
  // Invoice Number with yellow accent badge
  doc.setFillColor(250, 204, 21); // #FACC15
  doc.rect(15, 34, 45, 6, 'F');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.invoiceNumber, 17, 38.5);

  // Company Details (From)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text((company?.name || 'Company').toUpperCase(), 195, 25, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(company?.address || '', 195, 32, { align: 'right' });
  doc.text(company?.country || '', 195, 37, { align: 'right' });

  // Client Details (To)
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('BILL TO:', 15, 65);
  
  doc.setTextColor(15, 23, 42); // dark slate
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text((invoice?.clientName || 'Client').toUpperCase(), 15, 72);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text(invoice?.clientEmail || '', 15, 78);
  doc.text(invoice?.clientAddress || '', 15, 84);

  // Invoice Meta Info
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('DATE:', 140, 72);
  doc.text('DUE DATE:', 140, 78);
  
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice?.createdAt ? new Date(invoice.createdAt).toLocaleDateString() : '', 170, 72);
  doc.text(invoice?.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : '', 170, 78);

  // Custom Fields
  let customFieldsStartY = 95;
  if (invoice.customFields && invoice.customFields.length > 0) {
    invoice.customFields.forEach((field: any) => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 116, 139);
      doc.text(`${field.label.toUpperCase()}:`, 15, customFieldsStartY);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(15, 23, 42);
      doc.text(field.value, 45, customFieldsStartY);
      customFieldsStartY += 6;
    });
  }

  // Items Table
  const items = invoice?.items || [];
  const body = items.map((item: any) => [
    item.description || '',
    (item.quantity || 0).toString(),
    `$${(item.unitPrice || 0).toLocaleString()}`,
    `$${(item.amount || 0).toLocaleString()}`
  ]);

  autoTable(doc, {
    startY: Math.max(105, customFieldsStartY + 5),
    head: [['Description', 'Qty', 'Unit Price', 'Total']],
    body: body,
    theme: 'striped',
    headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 4 },
    columnStyles: {
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' }
    }
  });

  // Totals Summary Box
  const finalY = ((doc as any).lastAutoTable?.finalY || 130) + 12;
  
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(130, finalY - 5, 65, 34, 'F');
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.rect(130, finalY - 5, 65, 34, 'S');

  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont('helvetica', 'normal');
  doc.text('SUBTOTAL:', 135, finalY + 2);
  doc.text(`TAX (${invoice?.taxRate || 0}%):`, 135, finalY + 8);
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(130, finalY + 14, 195, finalY + 14);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('TOTAL AMOUNT:', 135, finalY + 23);

  // Totals Right Values
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`$${(invoice?.subtotal || 0).toLocaleString()}`, 190, finalY + 2, { align: 'right' });
  doc.text(`$${(invoice?.taxAmount || 0).toLocaleString()}`, 190, finalY + 8, { align: 'right' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(`$${(invoice?.totalAmount || 0).toLocaleString()}`, 190, finalY + 23, { align: 'right' });

  // Notes Box
  if (invoice.notes) {
    doc.setFillColor(254, 252, 232); // amber-50 light yellow
    doc.rect(15, finalY - 5, 100, 34, 'F');
    doc.setDrawColor(254, 240, 138); // amber-200
    doc.rect(15, finalY - 5, 100, 34, 'S');

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(133, 77, 14); // amber-800
    doc.text('NOTES / MEMO:', 20, finalY + 2);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(113, 63, 18);
    doc.text(invoice.notes, 20, finalY + 8, { maxWidth: 90 });
  }

  // Footer separator
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(15, 275, 195, 275);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Thank you for your business. For any questions, please contact the issuer.', 105, 282, { align: 'center' });

  return doc.output('arraybuffer');
};
