import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { UserOptions } from 'jspdf-autotable';

// Fix for jspdf-autotable typing
interface jsPDFWithPlugin extends jsPDF {
  autoTable: (options: UserOptions) => jsPDF;
}

export const generateSalarySlipPDF = async (record: any, company: any) => {
  const doc = new jsPDF() as jsPDFWithPlugin;

  // Header
  doc.setFillColor(250, 204, 21); // #FACC15
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(company.name.toUpperCase(), 15, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL SALARY SLIP', 15, 32);

  doc.setFontSize(16);
  doc.text('PAYSLIP', 160, 25);
  doc.setFontSize(10);
  doc.text(record.period.toUpperCase(), 160, 32);

  // Employee details
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('EMPLOYEE NAME', 15, 55);
  doc.text('EMAIL ADDRESS', 110, 55);
  
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(record.employeeName.toUpperCase(), 15, 62);
  doc.text(record.employeeEmail, 110, 62);

  // Table
  const tableData = [
    ['EARNINGS', 'AMOUNT'],
    ['Base Salary', `Rs ${record.baseSalary.toLocaleString()}`],
    ['Bonuses / Allowances', `Rs ${record.bonuses.toLocaleString()}`],
    ['', ''],
    ['DEDUCTIONS', 'AMOUNT'],
    ['Adjustments', `Rs ${record.deductions.toLocaleString()}`],
    ['', ''],
    ['TOTAL NET PAY', `Rs ${record.netPay.toLocaleString()}`]
  ];

  doc.autoTable({
    startY: 75,
    head: [['Description', 'Amount']],
    body: [
      ['Base Salary', `Rs ${record.baseSalary.toLocaleString()}`],
      ['Bonuses & Allowances', `Rs ${record.bonuses.toLocaleString()}`],
      ['Deductions', `- Rs ${record.deductions.toLocaleString()}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    styles: { font: 'helvetica', fontSize: 10 },
    columnStyles: {
      1: { halign: 'right', fontStyle: 'bold' }
    }
  });

  // Summary Box
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFillColor(243, 244, 246);
  doc.rect(120, finalY, 75, 25, 'F');
  doc.setDrawColor(0, 0, 0);
  doc.rect(120, finalY, 75, 25, 'S');

  doc.setFontSize(9);
  doc.text('NET TAKE HOME', 125, finalY + 10);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Rs ${record.netPay.toLocaleString()}`, 125, finalY + 20);

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  const dateStr = new Date().toLocaleDateString();
  doc.text(`Generated by Radical Ledger on ${dateStr}`, 15, 285);

  return doc.output('arraybuffer');
};
